{% set name = "creoleparser" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Creoleparser-{{ version }}.tar.gz
  sha256: 62999c115f3ece801ff31cdde7cab8f41df4ed95c189e1c6f02e7a036733a641

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - genshi >=0.4

test:
  imports:
    - creoleparser
    - creoleparser.core
    - creoleparser.dialects
    - creoleparser.elements
  commands:
    - pip check
  requires: 
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/garrison/creoleparser
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: 'a Python library for converting Creole wiki markup (aka wikicreole) for output on the web'
  dev_url: https://github.com/garrison/creoleparser

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
