schema_version: 1

context:
  name: creoleparser
  version: "0.7.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/Creoleparser-${{ version }}.tar.gz
  sha256: 62999c115f3ece801ff31cdde7cab8f41df4ed95c189e1c6f02e7a036733a641

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - genshi >=0.4

tests:
  - python:
      imports:
        - creoleparser
        - creoleparser.core
        - creoleparser.dialects
        - creoleparser.elements
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: MIT
  license_file: LICENSE.txt
  summary: a Python library for converting Creole wiki markup (aka wikicreole) for output on the web
  homepage: https://github.com/garrison/creoleparser
  repository: https://github.com/garrison/creoleparser

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
