travis:
  secure:
    BINSTAR_TOKEN: i2LW/zZ5RvbTDiZy2YseAPtjqTRBhkWkZw1QxIoHeoQWfkOUdg6KRjY8lg2dM3VRSjk/px7+7GHY1DZaOGO8lZ2XqC8LUTXBJ3JStfzqCHOLZRn8xU4Q3toR6hWZLA9Zy0gtyPs+jnAhG2muayEeWYCt/CkoYvT8Wl5ErVmH7yKmzah+KDPkoOsj6tVUAULIo5sdHTzP32zVENdMuDc4gvZ8VCMTkVuKzIp5H/MmYM6EtWe8DpF2inrvxcxyxoyFXvYUZG6kF1xaox0QWQKIkVb3rrt7/egSAP56xkze0T8CcLfws/fmsJ/eT7e7IJJzByfqSbybXvZ9Mou2sKBMGApViqFoGZ6pikSEoDES1pRNI8mdnFYctxU7lm4lPCoFu08GtwyEFqTTfKO6fLDnpipXq2eKdrHsRGxWyDDJh04Ngc+grOa9wjd3weSZGCwbOXbCN+3UQgaplGEpDEHbWVsgcRRSKK9Zw1+X2ALLtAK+kvFTAxQalRpqqr/hdZPyn4MTAX3p8tMHV0JPDCYOJGIkqfOvpLU5gEKpnkfNA71MKUmAj0rUGGNwiRL7XqFhpZsOEhvz9NqNBZJRZ7NRVdGeUWXR/ylwjrT8fhdb/jFJNTgxtU+eeLgWzmF9tCNmuAEZoqpDGybbrstoGpy4d+E5iiWgL84rHN9J50LeIxM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
