appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eJvGi2Wn3h7KhCddItTv4H/nVyORVyNfBzMmOFTiC2twz5J6eegyolqo5v+EuQFgCEYnX1JVQdsDTmZKSZ1OU1Jsb+TRR997T/QJkFxQ9Y/tUPBCxBdhr1gvpDKXeyAJ/vXcOJ6ajp1oLxsoP0Wkb0qVs/8OTBZRC2vCO7ORd8FeCd/imGSbJyuiYw8sU6PlXD7QdqtfV9HrHUqdowKMoSkYmSXKgrRllMHY7SU4hs1qs/Iu8SV5XXrQ8x04a5x6yal1nSp9udvH6cPuTXdU3RjKBdLzi0QOHfIsIxs6CwcG/N77AAHQJySywD6iFPraDy/2JNPdu2XwaOu30Vf1GWGPap9k7w/c1gNL22mxDZx6aWYr7IKbnVvR9nPxarvIHm1lUNSKL5331OUL2glcVGJ+mnufPaaYpk4vjexzQzYDT6rt0g6KmgJf06HwNZWVvHzuvp8aHIeAIp65WxNfmQRKpGRJJg11kbxq2NRlZqeuzM5VRbDUyI5eXfLOooBSq+C3oXWbS7J4DS/219HVZ0DX0dgDyiVqPZdzfzpo1SZlqNykkW/ieL3eEjuuN8zlU8/L6P3AtFaIN2zORiTXoLDjlcYrfr3IHuJCJ5e1cf2d+KC3TS4FdapDzRQNM6zyKjM0brU2IuGXCsINve/fnJfGLhsiC8vW2+AL/UOszM0=}
